[package]
name = "check_config"
version = "0.1.0"
authors = ["Antoine Lestrade"]

[dependencies]
ansi_term = "0.9.0"
getopts = "0.2.14"
lazy_static = "0.2.2"
regex = "0.1.80"
xml-rs = "0.3.4"
rustc-serialize = "0.3.21"
toml = "0.2.1"